In [10]:
#Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("../../../Github/Project_banking-fraud-analytics-dashboard-ml-risk/1_Cleaned_Dataset/clean_fraud_df.csv", header=0, index_col=0)

In [11]:
df["transaction_date"] = pd.to_datetime(df["transaction_date"], errors="coerce")
df["transaction_hour"] = pd.to_datetime(df["transaction_time"], format="%H:%M", errors="coerce").dt.hour
df["transaction_day"] = df["transaction_date"].dt.day
df["transaction_month"] = df["transaction_date"].dt.month
df["transaction_dayofweek"] = df["transaction_date"].dt.dayofweek

In [12]:

yes_no_cols = [
    "is_international_transaction",
    "is_new_merchant",
    "unusual_time_transaction"
]

for col in yes_no_cols:
    df[col] = df[col].map({"Yes": 1, "No": 0})

drop_cols = [
    "customer_id	",
    "device_id",
    "ip_address",
    "transaction_time",
    "transaction_date"
]

df = df.drop(columns=drop_cols, errors="ignore")
df

,transaction_amount_in_million,transaction_type,merchant_id,merchant_category,transaction_location,customer_home_location,distance_from_home,card_type,account_balance_in_million,daily_transaction_count,...,failed_transaction_count,unusual_time_transaction,previous_fraud_count,fraud_label,Country_x,Country_y,transaction_hour,transaction_day,transaction_month,transaction_dayofweek
customer_id,,,,,,,,,,,,,,,,,,,,,
24239.0,6.0,POS,97028.0,ATM,singapore,lahore,466.0,Credit,30.0,4.0,...,0.0,0,1.0,Normal,Singapore,Pakistan,10,8,3,5
77250.0,9.0,ATM,27515.0,ATM,singapore,lahore,215.0,Credit,4.0,4.0,...,1.0,0,1.0,Normal,Singapore,Pakistan,19,17,1,4
34294.0,3.0,POS,13810.0,Electronics,faisalabad,faisalabad,216.0,Debit,38.0,5.0,...,0.0,1,1.0,Normal,Pakistan,Pakistan,10,30,4,2
92041.0,1.0,Online,10501.0,Grocery,london,karachi,408.0,Debit,22.0,6.0,...,2.0,1,1.0,Normal,United Kingdom,Pakistan,14,21,2,4
71578.0,1.0,Online,53569.0,Electronics,singapore,islamabad,209.0,Debit,10.0,3.0,...,1.0,0,1.0,Normal,Singapore,Pakistan,4,11,4,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87401.0,4.0,POS,13857.0,Clothing,faisalabad,islamabad,571.0,Credit,34.0,1.0,...,1.0,0,0.0,Fraud,Pakistan,Pakistan,18,9,2,6
65425.0,4.0,Online,25552.0,Electronics,faisalabad,multan,433.0,Credit,4.0,4.0,...,2.0,0,0.0,Normal,Pakistan,Pakistan,21,12,3,2
14318.0,9.0,Online,41771.0,Electronics,singapore,lahore,161.0,Debit,21.0,5.0,...,0.0,0,1.0,Fraud,Singapore,Pakistan,11,4,3,1
55757.0,1.0,Online,72485.0,Clothing,bangkok,karachi,317.0,Credit,39.0,3.0,...,0.0,0,1.0,Normal,Thailand,Pakistan,8,25,3,1
57274.0,7.0,ATM,69446.0,Restaurant,bangkok,islamabad,494.0,Debit,23.0,3.0,...,0.0,1,1.0,Normal,Thailand,Pakistan,13,19,3,2

In [15]:
#only run code once, otherwise more and more indexes will be added to the DF
df = df.reset_index()
#df

In [16]:
#df = df.drop(["index", "customer_id", "unusual_time_transaction", "is_new_merchant", "is_international_transaction"], axis=1)
df = df.drop(["customer_id"], axis=1)
df

,transaction_amount_in_million,transaction_type,merchant_id,merchant_category,transaction_location,customer_home_location,distance_from_home,card_type,account_balance_in_million,daily_transaction_count,...,is_new_merchant,failed_transaction_count,unusual_time_transaction,fraud_label,Country_x,Country_y,transaction_hour,transaction_day,transaction_month,transaction_dayofweek
0,6.0,POS,97028.0,ATM,singapore,lahore,466.0,Credit,30.0,4.0,...,1,0.0,0,Normal,Singapore,Pakistan,10,8,3,5
1,9.0,ATM,27515.0,ATM,singapore,lahore,215.0,Credit,4.0,4.0,...,1,1.0,0,Normal,Singapore,Pakistan,19,17,1,4
2,3.0,POS,13810.0,Electronics,faisalabad,faisalabad,216.0,Debit,38.0,5.0,...,0,0.0,1,Normal,Pakistan,Pakistan,10,30,4,2
3,1.0,Online,10501.0,Grocery,london,karachi,408.0,Debit,22.0,6.0,...,1,2.0,1,Normal,United Kingdom,Pakistan,14,21,2,4
4,1.0,Online,53569.0,Electronics,singapore,islamabad,209.0,Debit,10.0,3.0,...,1,1.0,0,Normal,Singapore,Pakistan,4,11,4,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49848,4.0,POS,13857.0,Clothing,faisalabad,islamabad,571.0,Credit,34.0,1.0,...,0,1.0,0,Fraud,Pakistan,Pakistan,18,9,2,6
49849,4.0,Online,25552.0,Electronics,faisalabad,multan,433.0,Credit,4.0,4.0,...,1,2.0,0,Normal,Pakistan,Pakistan,21,12,3,2
49850,9.0,Online,41771.0,Electronics,singapore,lahore,161.0,Debit,21.0,5.0,...,1,0.0,0,Fraud,Singapore,Pakistan,11,4,3,1
49851,1.0,Online,72485.0,Clothing,bangkok,karachi,317.0,Credit,39.0,3.0,...,0,0.0,0,Normal,Thailand,Pakistan,8,25,3,1
49852,7.0,ATM,69446.0,Restaurant,bangkok,islamabad,494.0,Debit,23.0,3.0,...,1,0.0,1,Normal,Thailand,Pakistan,13,19,3,2

In [18]:
#Step 4: Split data - Train-Test Split
from sklearn.model_selection import train_test_split


X = df.drop(columns=["fraud_label"])
y = df["fraud_label"]
#print(x.head(1))
#print(y.head(1))


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

print("Train target ratio:")
print(y_train.value_counts(normalize=True))
print("Test target ration:")
print(y_test.value_counts(normalize=True))

Train target ratio:
fraud_label
Normal    0.951507
Fraud     0.048493
Name: proportion, dtype: float64
Test target ration:
fraud_label
Normal    0.95156
Fraud     0.04844
Name: proportion, dtype: float64

In [20]:
#Step 6: Building a preprocessing (separating numerical from categorical columns
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, StandardScaler

numeric_cols = X_train.select_dtypes(include=["int64", "float64"]).columns.tolist()
categorical_cols = X_train.select_dtypes(include=["object", "category"]).columns.tolist()

numeric_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

categorical_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("onehot", OneHotEncoder(handle_unknown="ignore"))
])

preprocessor = ColumnTransformer([
    ("num", numeric_pipeline, numeric_cols),
    ("cat", categorical_pipeline, categorical_cols)
])

In [ ]:
#Train a baseline model with class weights

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, ConfusionMatrixDisplay, roc_auc_score, average_precision_score
import matplotlib.pyplot as plt

baseline_model = Pipeline([
    ("preprocessor", preprocessor),
    ("model", LogisticRegression(max_iter=1000, class_weight="balanced"))
])

baseline_model.fit(X_train, y_train)

y_pred = baseline_model.predict(X_test)
y_proba = baseline_model.predict_proba(X_test)[:, 1]

print(classification_report(y_test, y_pred))
print("ROC-AUC:", roc_auc_score(y_test, y_proba))
print("PR-AUC:", average_precision_score(y_test, y_proba))

ConfusionMatrixDisplay.from_predictions(y_test, y_pred, cmap="Blues")
plt.title("Baseline Weighted Logistic Regression")
plt.show()

In [ ]:
from sklearn.ensemble import RandomForestClassifier

rf_model = Pipeline([
    ("preprocessor", preprocessor),
    ("model", RandomForestClassifier(
        n_estimators=300,
        random_state=42,
        class_weight="balanced",
        n_jobs=-1
    ))
])

rf_model.fit(X_train, y_train)

y_pred_rf = rf_model.predict(X_test)
y_proba_rf = rf_model.predict_proba(X_test)[:, 1]

print(classification_report(y_test, y_pred_rf))
print("ROC-AUC:", roc_auc_score(y_test, y_proba_rf))
print("PR-AUC:", average_precision_score(y_test, y_proba_rf))

ConfusionMatrixDisplay.from_predictions(y_test, y_pred_rf, cmap="Greens")
plt.title("Weighted Random Forest")
plt.show()